spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server.compression.enabled=true
server.compression.min-response-size=1024
server.compression.mime-types=application/json,text/plain,text/css,application/javascript
leaderboard.file=../../data/leaderboard.json
